
target 'PhotoCluster' do
  use_frameworks!

  pod 'LKAlertController', '~> 1.6'
  pod 'RealmSwift', '~> 1.0'
  pod 'CHTCollectionViewWaterfallLayout', '~> 0.9'
  pod 'BubbleTransition', '~> 2.0'

end
